version: '3'
services:
  api:
    container_name: mixlunch-service-api_api-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  grpc:
    container_name: mixlunch-service-api_grpc-server
    build:
      context: ./
      dockerfile: ./cmd/grpc/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: mixlunch-service-api_mysql
    command: mysqld --character-set-server=utf8mb4
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mixlunch
