// Code generated by MockGen. DO NOT EDIT.
// Source: ../tagservice/domain.go

// Package testmock is a generated GoMock package.
package testmock

import (
	gomock "github.com/golang/mock/gomock"
	tagservice "github.com/momotaro98/mixlunch-service-api/tagservice"
	reflect "reflect"
)

// MockTagServer is a mock of TagServer interface
type MockTagServer struct {
	ctrl     *gomock.Controller
	recorder *MockTagServerMockRecorder
}

// MockTagServerMockRecorder is the mock recorder for MockTagServer
type MockTagServerMockRecorder struct {
	mock *MockTagServer
}

// NewMockTagServer creates a new mock instance
func NewMockTagServer(ctrl *gomock.Controller) *MockTagServer {
	mock := &MockTagServer{ctrl: ctrl}
	mock.recorder = &MockTagServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagServer) EXPECT() *MockTagServerMockRecorder {
	return m.recorder
}

// GetTagsByTagType mocks base method
func (m *MockTagServer) GetTagsByTagType(tagType tagservice.TagType) ([]*tagservice.CategoryTags, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByTagType", tagType)
	ret0, _ := ret[0].([]*tagservice.CategoryTags)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByTagType indicates an expected call of GetTagsByTagType
func (mr *MockTagServerMockRecorder) GetTagsByTagType(tagType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByTagType", reflect.TypeOf((*MockTagServer)(nil).GetTagsByTagType), tagType)
}

// GetTagsByTagTypeAndTagIds mocks base method
func (m *MockTagServer) GetTagsByTagTypeAndTagIds(tagType tagservice.TagType, tagIds []uint16) ([]*tagservice.CategoryTags, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByTagTypeAndTagIds", tagType, tagIds)
	ret0, _ := ret[0].([]*tagservice.CategoryTags)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByTagTypeAndTagIds indicates an expected call of GetTagsByTagTypeAndTagIds
func (mr *MockTagServerMockRecorder) GetTagsByTagTypeAndTagIds(tagType, tagIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByTagTypeAndTagIds", reflect.TypeOf((*MockTagServer)(nil).GetTagsByTagTypeAndTagIds), tagType, tagIds)
}
