// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/momotaro98/mixlunch-service-api/logger"
	"github.com/momotaro98/mixlunch-service-api/partyservice"
	"github.com/momotaro98/mixlunch-service-api/tagservice"
	"github.com/momotaro98/mixlunch-service-api/userscheduleservice"
	"github.com/momotaro98/mixlunch-service-api/userservice"
)

// Injectors from wire.go:

func initializeGRPCServer(loggerConfig *logger.Config, usServiceDbConfig *userscheduleservice.Config, partyServiceConfig *partyservice.Config, userServiceConfig *userservice.Config, tagServiceConfig *tagservice.Config) *gRPCMixLunchServer {
	loggerLogger := logger.ProvideLogger(loggerConfig)
	sqlDb := userscheduleservice.ProvideDB(usServiceDbConfig)
	iUserScheduleQueryRepository := userscheduleservice.ProvideUserScheduleRepository(sqlDb)
	iUserScheduleCommandRepository := userscheduleservice.ProvideRealUserScheduleUpdateRepository(sqlDb)
	tagserviceSqlDb := tagservice.ProvideDB(tagServiceConfig)
	iTagQueryRepository := tagservice.ProvideTagQueryRepository(tagserviceSqlDb)
	tagServer := tagservice.ProvideTagServer(iTagQueryRepository)
	userScheduleServer := userscheduleservice.ProvideUserScheduleServer(iUserScheduleQueryRepository, iUserScheduleCommandRepository, tagServer)
	partyserviceSqlDb := partyservice.ProvideDB(partyServiceConfig)
	iPartyQueryRepository := partyservice.ProvidePartyQueryRepository(partyserviceSqlDb)
	iPartyCommandRepository := partyservice.ProvidePartyCommandRepository(partyserviceSqlDb)
	userserviceSqlDb := userservice.ProvideDB(userServiceConfig)
	iUserQueryRepository := userservice.ProvideUserQueryRepository(userserviceSqlDb)
	iUserCommandRepository := userservice.ProvideUserCommandRepository(userserviceSqlDb)
	userServer := userservice.ProvideUserServer(iUserQueryRepository, tagServer, iUserCommandRepository)
	app := partyservice.ProvideApp(partyServiceConfig)
	iChatRoomRepository := partyservice.ProvideChatRoomRepository(app)
	partyServer := partyservice.ProvidePartyServer(iPartyQueryRepository, iPartyCommandRepository, userServer, tagServer, iChatRoomRepository)
	mainGRPCMixLunchServer := provideGRPCMixLunchServer(loggerLogger, userScheduleServer, partyServer, userServer)
	return mainGRPCMixLunchServer
}
